name: Take screenshots

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '05 3 * * *'
    
permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - name: Set up Python 3.10
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
      with:
        python-version: "3.10"
    - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - name: Take shots
      run: |
        python get_pages.py
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
